# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zync_gpio/zync_gpio.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zync_gpio || ORIG_REF_NAME==zync_gpio} -quiet] -quiet

# IP: bd/zync_gpio/ip/zync_gpio_processing_system7_0_0/zync_gpio_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zync_gpio_processing_system7_0_0 || ORIG_REF_NAME==zync_gpio_processing_system7_0_0} -quiet] -quiet

# IP: bd/zync_gpio/ip/zync_gpio_axi_gpio_0_0/zync_gpio_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zync_gpio_axi_gpio_0_0 || ORIG_REF_NAME==zync_gpio_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zync_gpio/ip/zync_gpio_axi_gpio_0_2/zync_gpio_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zync_gpio_axi_gpio_0_2 || ORIG_REF_NAME==zync_gpio_axi_gpio_0_2} -quiet] -quiet

# IP: bd/zync_gpio/ip/zync_gpio_xbar_0/zync_gpio_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zync_gpio_xbar_0 || ORIG_REF_NAME==zync_gpio_xbar_0} -quiet] -quiet

# IP: bd/zync_gpio/ip/zync_gpio_auto_pc_0/zync_gpio_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zync_gpio_auto_pc_0 || ORIG_REF_NAME==zync_gpio_auto_pc_0} -quiet] -quiet

# IP: bd/zync_gpio/ip/zync_gpio_ps7_0_axi_periph_0/zync_gpio_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zync_gpio_ps7_0_axi_periph_0 || ORIG_REF_NAME==zync_gpio_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zync_gpio/ip/zync_gpio_rst_ps7_0_50M_0/zync_gpio_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zync_gpio_rst_ps7_0_50M_0 || ORIG_REF_NAME==zync_gpio_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/zync_gpio/zync_gpio_ooc.xdc
