# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/0522.xdc

# Block Designs: bd/zynq_custom/zynq_custom.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_custom || ORIG_REF_NAME==zynq_custom} -quiet] -quiet

# IP: bd/zynq_custom/ip/zynq_custom_processing_system7_0_0/zynq_custom_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_custom_processing_system7_0_0 || ORIG_REF_NAME==zynq_custom_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_custom/ip/zynq_custom_ps7_0_axi_periph_0/zynq_custom_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_custom_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_custom_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_custom/ip/zynq_custom_rst_ps7_0_50M_0/zynq_custom_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_custom_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_custom_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zynq_custom/ip/zynq_custom_auto_pc_1/zynq_custom_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_custom_auto_pc_1 || ORIG_REF_NAME==zynq_custom_auto_pc_1} -quiet] -quiet

# IP: bd/zynq_custom/ip/zynq_custom_myip_0_4/zynq_custom_myip_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_custom_myip_0_4 || ORIG_REF_NAME==zynq_custom_myip_0_4} -quiet] -quiet

# XDC: bd/zynq_custom/zynq_custom_ooc.xdc
