# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/project_1/project_1.srcs/sources_1/bd/zync_gpio/ip/zync_gpio_axi_gpio_0_2/zync_gpio_axi_gpio_0_2.xci
# IP: The module: 'zync_gpio_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/project_1/project_1.srcs/sources_1/bd/zync_gpio/ip/zync_gpio_axi_gpio_0_2/zync_gpio_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_gpio_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/project_1/project_1.srcs/sources_1/bd/zync_gpio/ip/zync_gpio_axi_gpio_0_2/zync_gpio_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_gpio_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/project_1/project_1.srcs/sources_1/bd/zync_gpio/ip/zync_gpio_axi_gpio_0_2/zync_gpio_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_gpio_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/project_1/project_1.srcs/sources_1/bd/zync_gpio/ip/zync_gpio_axi_gpio_0_2/zync_gpio_axi_gpio_0_2.xci
# IP: The module: 'zync_gpio_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/project_1/project_1.srcs/sources_1/bd/zync_gpio/ip/zync_gpio_axi_gpio_0_2/zync_gpio_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_gpio_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/project_1/project_1.srcs/sources_1/bd/zync_gpio/ip/zync_gpio_axi_gpio_0_2/zync_gpio_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_gpio_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/project_1/project_1.srcs/sources_1/bd/zync_gpio/ip/zync_gpio_axi_gpio_0_2/zync_gpio_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'zync_gpio_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
